plugins {
    id 'java'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.3'
    id 'com.gradleup.shadow' version '9.3.0'
    id 'maven-publish'
    id 'net.saliman.properties' version '1.6.0'
}

group = 'one.armelin'
version = '1.2.2'

configurations {
    create("shade")
    implementation {
        extendsFrom(configurations["shade"])
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(files("${project.HytaleInstallDir}/install/release/package/game/latest/Server/HytaleServer.jar"))

    // Discord integration
    implementation 'net.dv8tion:JDA:5.6.1'
    implementation 'club.minnced:discord-webhooks:0.8.4'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'blue.endless:jankson:1.2.3'

    // Shadow dependencies to include in JAR
    shade  'net.dv8tion:JDA:5.6.1'
    shade  'club.minnced:discord-webhooks:0.8.4'
    shade  'com.squareup.okhttp3:okhttp:4.12.0'
    shade  'blue.endless:jankson:1.2.3'
}

println("Using Hytale installation directory: ${project.HytaleInstallDir}")
println("Using Hytale Server jar: ${project.HytaleInstallDir}/install/release/package/game/latest/Server/HytaleServer.jar")

// Create the working directory to run the server if it does not already exist.
def serverRunDir = file("$projectDir/run/server")
if (!serverRunDir.exists()) {
    serverRunDir.mkdirs()
}

tasks.register('updatePluginManifest') {
    def manifestFile = file('src/main/resources/manifest.json')
    doLast {
        if (!manifestFile.exists()) {
            throw new GradleException("Could not find manifest.json at ${manifestFile.path}!")
        }
        def manifestJson = new groovy.json.JsonSlurper().parseText(manifestFile.text)
        manifestJson.Version = version
        manifestJson.IncludesAssetPack = includes_pack.toBoolean()
        manifestFile.text = groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(manifestJson))
    }
}

tasks.named('processResources') {
    dependsOn 'updatePluginManifest'
}

// Creates a run configuration in IDEA that will run the Hytale server with
// your plugin and the default assets.
idea.project.settings.runConfigurations {
    'HytaleServer'(org.jetbrains.gradle.ext.Application) {
        mainClass = 'com.hypixel.hytale.Main'
        moduleName = project.idea.module.name + '.main'
        programParameters = "--allow-op --disable-sentry --assets=${project.HytaleInstallDir}/install/release/package/game/latest/Assets.zip"
        if (includes_pack.toBoolean()) {
            programParameters += " --mods=${sourceSets.main.java.srcDirs.first().parentFile.absolutePath}"
        }
        if (load_user_mods.toBoolean()) {
            programParameters += " --mods=${project.HytaleInstallDir}/UserData/Mods"
        }
        workingDirectory = serverRunDir.absolutePath
    }
}


java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.shadowJar {
    archiveClassifier.set('')
    configurations = [project.configurations.shade]
    exclude 'META-INF/maven/**'
    exclude 'META-INF/services/cpw.**', 'META-INF/services/org.spongepowered.tools.obfuscation.service.IObfuscationService'
    exclude 'com/google/gson/**', 'org/sat4j/**'
    mergeServiceFiles()
}